# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  issues:
    exclude-rules:
      - path: _test\.go
      - path: vendor/
      - path: .git/

linters:
  enable-all: true
  disable:
    - exhaustruct
    - varnamelen
    - depguard
    - dogsled
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - goheader
    - goimports
    - golint
    - gosec
    - gosimple
    - grep-all
    - stylecheck
    - unconvert
    - wsl

formatter:
  gofumpt: true
  simple: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
