CREATE TABLE IF NOT EXISTS files (
  id UUID PRIMARY KEY,
  url TEXT NOT NULL,
  key VARCHAR(500) NOT NULL UNIQUE,
  size BIGINT NOT NULL,
  content_type VARCHAR(255) NOT NULL,
  original_name VARCHAR(500) NOT NULL,
  deleted_at TIMESTAMP,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
