// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/edwinhati/tagaroa/servers/finance/internal/application/account"
	"github.com/edwinhati/tagaroa/servers/finance/internal/application/budget"
	"github.com/edwinhati/tagaroa/servers/finance/internal/application/dashboard"
	"github.com/edwinhati/tagaroa/servers/finance/internal/application/investment"
	"github.com/edwinhati/tagaroa/servers/finance/internal/application/transaction"
	"github.com/edwinhati/tagaroa/servers/finance/internal/config"
	"github.com/edwinhati/tagaroa/servers/finance/internal/event"
	"github.com/edwinhati/tagaroa/servers/finance/internal/infrastructure/persistence/postgres"
	"github.com/edwinhati/tagaroa/servers/finance/internal/transport"
	"github.com/edwinhati/tagaroa/servers/finance/pkg/logger"
)

import (
	_ "github.com/jackc/pgx/v5/stdlib"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, func(), error) {
	sugaredLogger := logger.New()
	db, cleanup, err := ProvideDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	accountRepository := postgres.NewAccountRepository(db)
	producer, cleanup2, err := ProvideKafkaProducer(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	eventPublisher := ProvideEventPublisher(producer)
	domainEventPublisher := event.NewDomainEventPublisher(eventPublisher)
	service := account.NewService(accountRepository, domainEventPublisher)
	accountHandler := httphandler.NewAccountHandler(service)
	transactionRepository := postgres.NewTransactionRepository(db)
	transactionManager := postgres.NewTransactionManager(db)
	transactionService := transaction.NewService(transactionRepository, service, transactionManager, domainEventPublisher)
	transactionHandler := httphandler.NewTransactionHandler(transactionService)
	budgetRepository := postgres.NewBudgetRepository(db)
	budgetService := budget.NewService(budgetRepository, domainEventPublisher)
	budgetHandler := httphandler.NewBudgetHandler(budgetService)
	assetRepository := postgres.NewAssetRepository(db)
	liabilityRepository := postgres.NewLiabilityRepository(db)
	investmentService := investment.NewService(assetRepository, liabilityRepository)
	investmentHandler := httphandler.NewInvestmentHandler(investmentService)
	dashboardService := dashboard.NewService(accountRepository, transactionRepository, budgetRepository, assetRepository, liabilityRepository)
	dashboardHandler := httphandler.NewDashboardHandler(dashboardService, accountRepository, transactionRepository, budgetService, investmentService)
	oidcClient, err := ProvideOIDCClient(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := NewApp(cfg, sugaredLogger, db, accountHandler, transactionHandler, budgetHandler, investmentHandler, dashboardHandler, oidcClient)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
