export const CONSTANTS = {
  SERVER: {
    DEFAULT_PORT: 8080,
    SHUTDOWN_TIMEOUT_MS: 10_000,
  },

  RATE_LIMITS: {
    DEFAULT_WINDOW_SECONDS: 60,
    DEFAULT_MAX_REQUESTS: 100,
    SIGN_IN_WINDOW_SECONDS: 10,
    SIGN_IN_MAX_ATTEMPTS: 3,
    SIGN_UP_WINDOW_SECONDS: 60,
    SIGN_UP_MAX_ATTEMPTS: 5,
    RESET_PASSWORD_WINDOW_SECONDS: 300,
    RESET_PASSWORD_MAX_ATTEMPTS: 3,
    VERIFY_EMAIL_WINDOW_SECONDS: 60,
    VERIFY_EMAIL_MAX_ATTEMPTS: 5,
    OAUTH_AUTHORIZE_WINDOW_SECONDS: 60,
    OAUTH_AUTHORIZE_MAX_ATTEMPTS: 20,
    OAUTH_TOKEN_WINDOW_SECONDS: 60,
    OAUTH_TOKEN_MAX_ATTEMPTS: 30,
    OAUTH_USERINFO_WINDOW_SECONDS: 60,
    OAUTH_USERINFO_MAX_ATTEMPTS: 200,
  },

  JWT: {
    EXPIRATION_TIME: "15m",
    ALGORITHM: "RS256",
    MODULUS_LENGTH: 2048,
  },

  SESSIONS: {
    MAX_PER_USER: 3,
  },

  CORS: {
    MAX_AGE_SECONDS: 86400,
  },

  LOG_LEVEL: {
    DEFAULT: "info",
    PRODUCTION: "error",
    DEVELOPMENT: "info",
  },
} as const;

export type ConstantValues = (typeof CONSTANTS)[keyof typeof CONSTANTS];
