---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      k8s_kubeconfig: "{{ playbook_dir }}/../../terraform/envs/dev/kubeconfig"
