name: Continuous Delivery

on:
  workflow_call:
    inputs:
      is_main_branch:
        required: true
        type: boolean

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      is_main_branch: ${{ inputs.is_main_branch }}
    secrets: inherit

  deploy:
    needs: release
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.release.outputs.version }}
      is_main_branch: ${{ inputs.is_main_branch }}
      released: ${{ needs.release.outputs.released }}
    secrets: inherit
