name: Continuous Integration

on:
  workflow_call:
    secrets:
      TURBO_TOKEN:
        required: false
      TURBO_TEAM:
        required: false

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
