name: CI/CD Pipeline

on:
  push:
    branches: [main, develop, "feature/**", "hotfix/**"]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  cd:
    name: Continuous Deployment
    needs: ci
    if: github.event_name == 'push'
    uses: ./.github/workflows/cd.yml
    with:
      is_main_branch: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
